services:
  - type: web
    name: pirateradio-icecast
    env: docker
    dockerfilePath: ./icecast/Dockerfile
    dockerContext: ./icecast
    plan: free
    envVars:
      - key: ICECAST_SOURCE_PASSWORD
        sync: false
      - key: ICECAST_ADMIN_PASSWORD
        sync: false

  - type: web
    name: pirateradio-bridge
    env: docker
    dockerfilePath: ./bridge/Dockerfile
    dockerContext: ./bridge
    plan: free
    envVars:
      - key: ICECAST_HOST
        fromService:
          type: web
          name: pirateradio-icecast
          property: host
      - key: ICECAST_PORT
        fromService:
          type: web
          name: pirateradio-icecast
          property: port
      - key: ICECAST_SOURCE_PASSWORD
        sync: false
      - key: ICECAST_MOUNT
        value: /radio.webm
      - key: BROADCAST_PASSWORD
        sync: false
